name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      
      - name: Install pnpm
      - run: curl -fsSL https://get.pnpm.io/install.sh | sh -

      - name: Install dependencies
      - run: pnpm install

      - name: SSG
      - run: pnpm run generate

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: .output/public